name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.AWS_REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.AWS_REMOTE_USER }}
          TARGET: ${{ secrets.AWS_REMOTE_TARGET }}
